// backend/src/modules/attendance/models/AttendanceScanLog.js

const mongoose = require('mongoose')

const { Schema } = mongoose

const SCAN_RESULTS = [
  'SUCCESS',
  'INVALID_FORMAT',
  'EMPLOYEE_NOT_FOUND',
  'EMPLOYEE_INACTIVE',
  'SYSTEM_ERROR',
]

function s(value) {
  return String(value ?? '').trim()
}

function upper(value) {
  return s(value).toUpperCase()
}

const attendanceScanLogSchema = new Schema(
  {
    rawScannedValue: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
    },

    normalizedScannedValue: {
      type: String,
      default: '',
      trim: true,
      maxlength: 100,
    },

    // Cambodia work date generated by backend, never trusted from browser.
    attendanceDate: {
      type: String,
      required: true,
      trim: true,
      maxlength: 10,
    },

    scannedAt: {
      type: Date,
      required: true,
      default: Date.now,
    },

    result: {
      type: String,
      enum: SCAN_RESULTS,
      required: true,
      default: 'SUCCESS',
      trim: true,
    },

    reason: {
      type: String,
      default: '',
      trim: true,
      maxlength: 500,
    },

    stationName: {
      type: String,
      default: 'SCAN_STATION',
      trim: true,
      maxlength: 100,
    },

    employeeId: {
      type: Schema.Types.ObjectId,
      ref: 'Employee',
      default: null,
    },

    employeeNo: {
      type: String,
      default: '',
      trim: true,
      maxlength: 50,
    },

    employeeName: {
      type: String,
      default: '',
      trim: true,
      maxlength: 200,
    },

    attendanceRecordId: {
      type: Schema.Types.ObjectId,
      ref: 'AttendanceRecord',
      default: null,
    },

    createdBy: {
      type: Schema.Types.ObjectId,
      ref: 'Account',
      default: null,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  },
)

attendanceScanLogSchema.pre('validate', function normalize(next) {
  this.rawScannedValue = s(this.rawScannedValue)
  this.normalizedScannedValue = upper(this.normalizedScannedValue || this.rawScannedValue)
  this.attendanceDate = s(this.attendanceDate)
  this.result = upper(this.result || 'SUCCESS')
  this.reason = s(this.reason)
  this.stationName = s(this.stationName || 'SCAN_STATION')
  this.employeeNo = upper(this.employeeNo)
  this.employeeName = s(this.employeeName)
  next()
})

attendanceScanLogSchema.index({ attendanceDate: -1, scannedAt: -1 })
attendanceScanLogSchema.index({ attendanceDate: -1, result: 1, scannedAt: -1 })
attendanceScanLogSchema.index({ normalizedScannedValue: 1, scannedAt: -1 })
attendanceScanLogSchema.index({ employeeId: 1, attendanceDate: -1 })

module.exports = mongoose.model('AttendanceScanLog', attendanceScanLogSchema)
